config/routes.rb
Livingtranscript::Application.routes.draw do
  devise_for :users

  resources :entries, :only => ["index", "new", "create", "edit", "update", "destroy", "show"]
  resources :tags, :only => ["index"]
  resources :admins, :only => ["index"]
  resources :recommendations, :only => ["show", "update"]
  resources :tabs, :only => ["index"]
  match "/recommendations/new/:id" => "recommendations#new", :as => "new_requested_recommendation"

  root :to => "home#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= csrf_meta_tag %>
  <title>Living Transcript</title>
  <%= stylesheet_link_tag :all %>
  <%= stylesheet_link_tag 'smoothness/jquery-ui-1.8.16.custom' %>
  <link rel="stylesheet/less" type="text/css" href="/stylesheets/lib/bootstrap.less">
  <%= javascript_include_tag 'jquery-1.6.2.min' %>
  <%= javascript_include_tag 'jquery-ui-1.8.16.custom.min' %>
  <%= javascript_include_tag 'jquery.form' %>
  <%= javascript_include_tag 'jquery.tagsinput.min' %>
  <%= javascript_include_tag 'jquery.tagcloud' %>
  <%= javascript_include_tag 'jquery.ba-bbq.min' %>
  <%= javascript_include_tag 'jquery.color' %>
  <%= javascript_include_tag 'bootstrap-tabs' %>
  <%= javascript_include_tag 'bootstrap-alerts' %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag 'less-1.1.3.min.js' %>
</head>
<body>
  <div id="work-page-container" class="container">
    <div class="topbar-wrapper" style="z-index: 5;">
      <div class="topbar">
        <div class="topbar-inner">
          <div class="container">
            <h3><%= link_to 'Living Transcript', root_path %></h3>
            <%- if current_user -%>
              <ul class="nav secondary-nav">
                <li>
                <span>Welcome back,&nbsp;<%= current_user.full_name %></span>
                </li>
                <%- if current_user.is_admin? -%>
                <li>
                    <%= link_to('Admin', admins_path) %>
                </li>
                <%- end -%>
                <li>
                    <%= link_to('Account', edit_user_registration_path) %>
                </li>
                <li>
                    <%= link_to('Logout', destroy_user_session_path, :method => 'delete') %>
                </li>
              </ul>
            <%- end -%>
          </div>
        </div>
      </div>
    </div>
    <div id="content" class="row">
      <%= yield %>
    </div>
  </div>
</body>
</html>